#!/bin/bash
# Nightly pg_dump of grocery_db to a host-mounted directory (#60).
#
# Why this exists: everything the household cannot re-derive - recipes, recipe
# ingredients, meal-plan history, cook_depletions, pantry, grocery list, profiles
# - lives only in the `db_data` Docker volume. Prices are re-scrapable; recipes
# are not. Before this there was no backup of any kind, so one `docker compose
# down -v`, one disk failure, or one botched migration was unrecoverable.
#
# Writes to /backups, which docker-compose.yml bind-mounts to ../backups on the
# host. That is deliberately OUTSIDE the db_data volume: a backup that lives in
# the thing it is backing up is not a backup.
#
# A loop rather than a cron entry, because the postgres:16 image has no cron and
# adding one to get a single daily job is more machinery than the job needs. The
# scraper image does use cron (and needs root for /etc/cron.d); this one doesn't.
#
# Failure is loud rather than silent. A backup that quietly stopped working is
# worse than no backup, because it produces confidence - so every attempt logs a
# timestamped OK or FAILED line to stdout, where `docker logs db_backup` shows it.

set -uo pipefail

KEEP_DAYS="${BACKUP_KEEP_DAYS:-14}"
HOUR="${BACKUP_HOUR:-3}"
MINUTE="${BACKUP_MINUTE:-30}"
INCLUDE_PRICES="${BACKUP_INCLUDE_PRICES:-false}"
DIR="${BACKUP_DIR:-/backups}"
# Don't take a second backup within this many seconds of the last one, so a
# crash-looping container can't fill the disk with dumps.
MIN_INTERVAL_SECONDS="${BACKUP_MIN_INTERVAL_SECONDS:-3600}"

log() { echo "[backup $(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

newest_backup() {
    ls -1t "${DIR}"/grocery_db-*.sql.gz 2>/dev/null | head -n1
}

next_run_epoch() {
    # GNU date, which the Debian-based postgres image provides. If the arithmetic
    # ever fails, fall back to "one day from now" rather than exiting - a backup
    # that runs at the wrong hour still beats one that stops.
    local now target
    now=$(date +%s)
    if ! target=$(date -d "today ${HOUR}:${MINUTE}" +%s 2>/dev/null); then
        echo $((now + 86400))
        return
    fi
    if [ "$target" -le "$now" ]; then
        target=$(date -d "tomorrow ${HOUR}:${MINUTE}" +%s)
    fi
    echo "$target"
}

do_backup() {
    local stamp out tmp args=()
    stamp=$(date -u +%Y%m%d-%H%M%S)
    out="${DIR}/grocery_db-${stamp}.sql.gz"
    tmp="${out}.tmp"

    # grocery_prices is by far the largest table (46,501 rows from a SINGLE
    # scrape; ~17M rows/year at the daily schedule) and it is the one thing here
    # that can be regenerated by running the scraper again. So the default
    # excludes its ROWS while keeping its schema and the grocery_prices_latest
    # view, which keeps dumps in the kilobytes instead of gigabytes and makes the
    # nightly job fast enough to not matter.
    #
    # This is a real tradeoff, not a free win: restoring such a dump loses price
    # history, so /history's price context and any trend view go back to whatever
    # the next scrape produces. Set BACKUP_INCLUDE_PRICES=true to keep it. The
    # log line states which mode ran, every time, so nobody has to guess what a
    # given dump contains.
    if [ "$INCLUDE_PRICES" != "true" ]; then
        args+=(--exclude-table-data=grocery_prices)
    fi

    # Write to .tmp and rename, so a dump that dies halfway never leaves a
    # truncated file that looks like a good backup. `pipefail` is what makes the
    # `if` see pg_dump's failure rather than gzip's success.
    if pg_dump --format=plain --no-owner --no-privileges "${args[@]}" | gzip > "$tmp"; then
        mv "$tmp" "$out"
        log "OK ${out} $(du -h "$out" | cut -f1) prices_data=${INCLUDE_PRICES}"
        return 0
    fi
    rm -f "$tmp"
    log "FAILED pg_dump|gzip exited non-zero; no backup written this run" >&2
    return 1
}

prune() {
    local f count=0
    # -mtime +N means strictly older than N 24h periods. Only ever matches this
    # script's own filename pattern, so a stray file in the directory is left
    # alone rather than deleted.
    while IFS= read -r f; do
        [ -n "$f" ] || continue
        rm -f "$f" && log "pruned ${f} (older than ${KEEP_DAYS} days)" && count=$((count + 1))
    done < <(find "${DIR}" -maxdepth 1 -name 'grocery_db-*.sql.gz' -mtime +"${KEEP_DAYS}" 2>/dev/null)
    return 0
}

mkdir -p "$DIR"
log "starting: daily at $(printf '%02d:%02d' "$HOUR" "$MINUTE") container-local time, keeping ${KEEP_DAYS} days, prices_data_included=${INCLUDE_PRICES}, dir=${DIR}"

# Back up once on startup so a fresh deployment is protected from minute one
# instead of after the first 03:30 - unless a recent backup already exists, so a
# restart doesn't immediately produce another dump.
latest=$(newest_backup)
if [ -z "$latest" ]; then
    do_backup || log "initial backup failed; will retry at the next scheduled time"
else
    age=$(( $(date +%s) - $(date -r "$latest" +%s) ))
    if [ "$age" -ge "$MIN_INTERVAL_SECONDS" ]; then
        do_backup || log "startup backup failed; will retry at the next scheduled time"
    else
        log "newest backup is ${age}s old (< ${MIN_INTERVAL_SECONDS}s), skipping startup run"
    fi
fi
prune

while true; do
    now=$(date +%s)
    target=$(next_run_epoch)
    wait_for=$((target - now))
    if [ "$wait_for" -gt 0 ]; then
        sleep "$wait_for"
    fi
    do_backup || true
    prune
    # Nudge past the top of the minute so next_run_epoch computes tomorrow rather
    # than firing twice in the same minute.
    sleep 61
done
