#!/bin/bash
# Nightly pg_dump of grocery_db to a host-mounted directory (#60).
#
# Why this exists: everything the household cannot re-derive - recipes, recipe
# ingredients, meal-plan history, cook_depletions, pantry, grocery list, profiles
# - lives only in the `db_data` Docker volume. Prices are re-scrapable; recipes
# are not. Before this there was no backup of any kind, so one `docker compose
# down -v`, one disk failure, or one botched migration was unrecoverable.
#
# Writes to /backups, which docker-compose.yml bind-mounts to ../backups on the
# host. That is deliberately OUTSIDE the db_data volume: a backup that lives in
# the thing it is backing up is not a backup.
#
# A loop rather than a cron entry, because the postgres:16 image has no cron and
# adding one to get a single daily job is more machinery than the job needs. The
# scraper image does use cron (and needs root for /etc/cron.d); this one doesn't.
#
# Failure is loud rather than silent. A backup that quietly stopped working is
# worse than no backup, because it produces confidence - so every attempt logs a
# timestamped OK or FAILED line to stdout, where `docker logs db_backup` shows it.
#
# NOTE: `set -e` is deliberately absent. The loop has to survive a failed dump and
# try again tomorrow; aborting the container on the first transient database error
# would trade a missed backup for no backups at all. `set -u` and `pipefail` are
# kept because those catch real bugs (an unset variable, a pg_dump failure hidden
# behind a succeeding gzip) without killing the loop.

set -uo pipefail

DIR="${BACKUP_DIR:-/backups}"

log() { echo "[backup $(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

# Config comes from the environment, so a typo'd value must not silently change
# behaviour. Each of these was verified to fail in a way that is easy to miss: a
# non-numeric BACKUP_KEEP_DAYS makes `find -mtime +abc` error out with stderr
# discarded, so pruning silently stops forever and nothing is logged; a
# non-numeric HOUR makes `date -d` fail into the 24h fallback while the startup
# banner cheerfully prints "daily at 00:00". Validate once, loudly, and fall back
# to the default rather than to something surprising.
int_or_default() {
    local name="$1" raw="$2" default="$3"
    if [[ "$raw" =~ ^[0-9]+$ ]]; then
        printf '%s' "$raw"
    else
        log "WARNING ${name}=${raw:-<unset>} is not a non-negative integer; using ${default}" >&2
        printf '%s' "$default"
    fi
}

KEEP_DAYS="$(int_or_default BACKUP_KEEP_DAYS "${BACKUP_KEEP_DAYS:-14}" 14)"
HOUR="$(int_or_default BACKUP_HOUR "${BACKUP_HOUR:-3}" 3)"
MINUTE="$(int_or_default BACKUP_MINUTE "${BACKUP_MINUTE:-30}" 30)"
INCLUDE_PRICES="${BACKUP_INCLUDE_PRICES:-false}"
# Don't take two backups within this window, so a crash-looping container can't
# fill the disk with dumps and a start just before the scheduled minute can't
# produce a second dump seconds later.
MIN_INTERVAL_SECONDS="$(int_or_default BACKUP_MIN_INTERVAL_SECONDS "${BACKUP_MIN_INTERVAL_SECONDS:-3600}" 3600)"

newest_backup() {
    ls -1t "${DIR}"/grocery_db-*.sql.gz 2>/dev/null | head -n1
}

newest_backup_age_seconds() {
    local latest
    latest=$(newest_backup)
    [ -n "$latest" ] || { echo 999999999; return; }
    echo $(( $(date +%s) - $(date -r "$latest" +%s) ))
}

next_run_epoch() {
    # GNU date, which the Debian-based postgres image provides. If the arithmetic
    # ever fails, fall back to "one day from now" rather than exiting - a backup
    # that runs at the wrong hour still beats one that stops. HOUR and MINUTE are
    # already validated as integers above, so this fallback is for a date failure
    # rather than for bad config.
    local now target
    now=$(date +%s)
    if ! target=$(date -d "today ${HOUR}:${MINUTE}" +%s 2>/dev/null); then
        log "WARNING could not parse ${HOUR}:${MINUTE} as a time of day; next run in 24h" >&2
        echo $((now + 86400))
        return
    fi
    if [ "$target" -le "$now" ]; then
        target=$(date -d "tomorrow ${HOUR}:${MINUTE}" +%s)
    fi
    echo "$target"
}

do_backup() {
    local stamp out tmp args=()
    stamp=$(date -u +%Y%m%d-%H%M%S)
    out="${DIR}/grocery_db-${stamp}.sql.gz"
    tmp="${out}.tmp"

    # grocery_prices is by far the largest table (46,501 rows from a SINGLE
    # scrape; ~17M rows/year at the daily schedule) and it is the one thing here
    # that can be regenerated by running the scraper again. So the default
    # excludes its ROWS while keeping its schema and the grocery_prices_latest
    # view, which keeps dumps in the kilobytes instead of gigabytes and makes the
    # nightly job fast enough to not matter.
    #
    # This is a real tradeoff, not a free win: restoring such a dump loses price
    # history, so anything depending on past prices starts again from the next
    # scrape. Set BACKUP_INCLUDE_PRICES=true to keep it. The log line states which
    # mode ran, every time, so nobody has to guess what a given dump contains.
    #
    # Exact table name, no wildcard, so grocery_prices_latest is unaffected.
    if [ "$INCLUDE_PRICES" != "true" ]; then
        args+=(--exclude-table-data=grocery_prices)
    fi

    # Write to .tmp and rename, so a dump that dies halfway never leaves a
    # truncated file that looks like a good backup. `pipefail` is what makes the
    # `if` see pg_dump's failure rather than gzip's success.
    #
    # The `mv` is inside the same `if` on purpose. An earlier version had it after
    # the gzip check, so a failed rename - full disk, permissions, a read-only
    # mount - still logged "OK" with an empty size and returned 0. That is exactly
    # the false confidence this script exists to avoid.
    if pg_dump --format=plain --no-owner --no-privileges "${args[@]}" | gzip > "$tmp" \
        && mv "$tmp" "$out"; then
        log "OK ${out} $(du -h "$out" | cut -f1) prices_data=${INCLUDE_PRICES}"
        return 0
    fi
    rm -f "$tmp"
    log "FAILED pg_dump|gzip|mv did not complete; no backup written this run" >&2
    return 1
}

prune() {
    local f pruned=0
    # -mtime +N means strictly older than N 24h periods. Only ever matches this
    # script's own filename patterns, so a stray file in the directory is left
    # alone rather than deleted.
    #
    # The .tmp pattern matters: `mv` never runs if the container is killed
    # mid-dump, and bash-as-PID-1 ignores SIGTERM so `docker compose stop` waits
    # out its grace period and then SIGKILLs. Every interrupted dump therefore
    # leaves an orphan that the .sql.gz pattern would never match. Harmless at
    # kilobyte scale, but README documents BACKUP_INCLUDE_PRICES=true, where dumps
    # are gigabytes and orphans would fill the disk - which #60's done bar
    # explicitly forbids.
    while IFS= read -r f; do
        [ -n "$f" ] || continue
        rm -f "$f" && { log "pruned ${f} (older than ${KEEP_DAYS} days)"; pruned=$((pruned + 1)); }
    done < <(find "${DIR}" -maxdepth 1 \
        \( -name 'grocery_db-*.sql.gz' -o -name 'grocery_db-*.sql.gz.tmp' \) \
        -mtime +"${KEEP_DAYS}" 2>/dev/null)
    [ "$pruned" -eq 0 ] || log "prune complete: removed ${pruned} file(s)"
    return 0
}

mkdir -p "$DIR"
log "starting: daily at $(printf '%02d:%02d' "$HOUR" "$MINUTE") container-local time (UTC in this image), keeping ${KEEP_DAYS} days, prices_data_included=${INCLUDE_PRICES}, dir=${DIR}"

# Back up once on startup so a fresh deployment is protected from minute one
# instead of after the first 03:30 - unless a recent backup already exists, so a
# restart doesn't immediately produce another dump.
age=$(newest_backup_age_seconds)
if [ "$age" -ge "$MIN_INTERVAL_SECONDS" ]; then
    do_backup || log "startup backup failed; will retry at the next scheduled time"
else
    log "newest backup is ${age}s old (< ${MIN_INTERVAL_SECONDS}s), skipping startup run"
fi
prune

while true; do
    now=$(date +%s)
    target=$(next_run_epoch)
    wait_for=$((target - now))
    if [ "$wait_for" -gt 0 ]; then
        sleep "$wait_for"
    fi
    # Same guard as the startup run: starting the container just before the
    # scheduled minute would otherwise produce two dumps within a minute.
    age=$(newest_backup_age_seconds)
    if [ "$age" -ge "$MIN_INTERVAL_SECONDS" ]; then
        do_backup || true
    else
        log "newest backup is ${age}s old (< ${MIN_INTERVAL_SECONDS}s), skipping scheduled run"
    fi
    prune
    # Nudge past the top of the minute so next_run_epoch computes tomorrow rather
    # than firing twice in the same minute.
    sleep 61
done
