version: '3.8'

services:
  grocery_scraper:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=grocery_db
      - DB_USER=user
      - DB_PASS=password
    networks:
      - my_network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grocery_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data:
